### PR TITLE
[WIP] Integrate odoc

### PR DESCRIPTION
**Pull request by rizo**
First steps to solve https://github.com/esy-ocaml/hello-reason/issues/13.

Currently this will generate OCaml syntax as described in https://github.com/esy-ocaml/hello-reason/issues/13. I haven't decided yet what's the best way to pass the syntax option to odoc.

This is how it looks:

odoc

I'll try to fix the issues mentioned in #13 next. Ideas/suggestions are welcome.

### CODE REVIEW

**Comment by andreypopp** [comment]
Nice!

What do you think about adding an index page with some narrative-style docs which references API docs? Well, would be even cooler if odoc could use `README.md` as a such page.

**Comment by rizo** [comment]
> What do you think about adding an index page with some narrative-style docs

That's the plan! I want to add a custom `index.mld` file for the library.

> Well, would be even cooler if odoc could use README.md as a such page.

Currently `odoc` does not support that. I would be useful but I'm worried that some important features (like symbol cross-referencing) would not be available in markdown. This is also related to the idea that @jordwalke and I discussed which was essentially implementing a ppx to transform markdown into ocamldoc. I'd say for now let's keep things focused on polishing the odoc's integration in it's current shape and add new features later.

**Comment by rizo** [comment]
As a general thought: the content of the README might significantly differ from what one might want to write as a library guide. I understand that rich READMEs are somewhat common, but we'll have very handy features in odoc like executable examples, versioned cross-package references, type-on-hover tooltips, _etc_. that will help library authors produce excellent docs. I'd personally reserve READMEs for general overview of the package, advanced building instructions and contribution guide.

In any case I believe supporting markdown is going to be an important feature so we might end up having something that works for both use cases.

**Comment by andreypopp** [comment]
> I'd say for now let's keep things focused on polishing the odoc's integration in it's current shape and add new features later.

Totally agree. Sorry for hijacking the discussion with my personal wishlist :-).

>  I understand that rich READMEs are somewhat common, but we'll have very handy features in odoc like executable examples, versioned cross-package references, type-on-hover tooltips, etc. 

I think https://github.com/realworldocaml/mdx would help there.

> In any case I believe supporting markdown is going to be an important feature so we might end up having something that works for both use cases.

👍

**Comment by ulrikstrid** [comment]
Can we close this as we landed #17 ?

**Comment by rizo** [comment]
Thanks for finishing this @ulrikstrid!

**Pull request closed without merging**
