### PR TITLE
[Chore] buildDev and add --release

### PR DESCRIPTION
**Pull request by Et7f3**
This PR add buildDev as explained here https://esy.sh/docs/en/configuration.html#esybuilddev.

It add `--release` to prevent bad dependencies. One example is [re-web](https://github.com/yawaramin/re-web/blob/4c2b55e2c28ef8341bce5861b2770a4e31cbebb7/package.json#L7) @tcoopman tried to build it as dependencies but alcotest was required. This could be catched with --release in the CI. Also the json of `re-web` is very similar to this repo that is why I PR here.

Also when grepping `esy build` I have found 1 useless file.

Also this project pull rely but is is not used. Should I add a small function/test to show example in this PR ?

### CODE REVIEW

**Review by ulrikstrid — APPROVED** [review]
Looks good to me, we would love a PR with a nice rely starter setup. I think we had that at some point, not sure why we don't now.

**Comment by Et7f3** [comment]
I have rebased onto master because #60 was merged in the meantime.

**Comment by Et7f3** [comment]
The hello-reason.install file is builded with the `-p` option of dune and not with the with the `--only-package`. I have tested with another name of the json file and this work but I feel hacky. I think we can use `dune exec` here.

**Comment by ulrikstrid** [comment]
I'm slightly concerned that we need that install to make it work since this is a very simple project. I wonder if we need to do changes somewhere to just have the default install work.

**Pull request merged**
